### ISSUE TITLE
Models have occassional final time step truncation

### ISSUE THREAD

**Issue by tomasjames** [uclchem/UCLCHEM#11]
Occassional models, when run with `grid.py`, have their final time step truncated such that the abundance of some molecules is not written out. 

This is leading to errors when plotting these abundances as a function of time, as the array dimensions do not match (i.e. python is able to find the time step for that entry, but not the molecular abundance as it has been truncated).

**Comment by jonholdship** [comment]
Bug fixed! Added close statements to wrap.f90, writing to file is completed before file is closed and so no truncation occurs.
