### ISSUE TITLE
Refractory Species

### ISSUE THREAD

**Issue by jonholdship** [uclchem/UCLCHEM#13]
Currently every species is either in the gas phase or in the ices and all frozen species are treated the same way. However, certain species are refractory and will not sublimate at high temperatures.

It would be useful to introduce a flag that prevents a species from being removed from the dust through thermal sublimation.

One could then edit the shock modules so that we include both mantle and core sputtering using the expressions from Jimenez-Serra 2008. Currently, we assume mantle sputtering for all species and simply deplete abundances of core species.

**Comment by tomasjames** [comment]
Could we have `MakeRates.py` flag a species as being refectory, and then use this flag to allow UCLCHEM to leave it on the ices at high temperature?

It might be the grain file that needs the flag (rather than MakeRates specifically).

**Comment by jonholdship** [comment]
I think that's the solution: a flag in the species file that is picked up by MakeRates.
It should affect what comes off in cloud.f90's sublimation and it should stop refractory species from being included in the mantle calculation.

**Comment by tomasjames** [comment]
In the interest of compatibility, it might be worthwhile (until we can update all the modules to the new standard) keeping the refactory species file separate from the standard species file as otherwise every module will break 😮

**Comment by jonholdship** [comment]
I think if we change the underlying structures like grainList, we can do the change at a makerates level without affecting the modules.

**Comment by jonholdship** [comment]
Refractory species achieved by adding your bulk species such as "@SI" to the input species list and giving them an extremely high binding energy, this overrules MakaRates automatically adding @SI with the BE of H2O.
